// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto.Base.BackEnd.Infra.Contexto;

namespace Projeto.Base.BackEnd.Infra.Migrations
{
    [DbContext(typeof(ModeloDbContext))]
    [Migration("20220816183610_CorrecaoClubeId")]
    partial class CorrecaoClubeId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Projeto.Base.BackEnd.Domain.Entidades.Clubes.Clube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AnoFundacao")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UrlRedeSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .IsClustered(false);

                    b.ToTable("Clube");
                });

            modelBuilder.Entity("Projeto.Base.BackEnd.Domain.Entidades.Estadios.Estadio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("ClubeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .IsClustered(false);

                    b.HasIndex("ClubeId")
                        .IsUnique();

                    b.ToTable("Estadio");
                });

            modelBuilder.Entity("Projeto.Base.BackEnd.Domain.Entidades.Estadios.Estadio", b =>
                {
                    b.HasOne("Projeto.Base.BackEnd.Domain.Entidades.Clubes.Clube", "Clube")
                        .WithOne("Estadio")
                        .HasForeignKey("Projeto.Base.BackEnd.Domain.Entidades.Estadios.Estadio", "ClubeId")
                        .HasConstraintName("Clube_Id_Fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clube");
                });

            modelBuilder.Entity("Projeto.Base.BackEnd.Domain.Entidades.Clubes.Clube", b =>
                {
                    b.Navigation("Estadio");
                });
#pragma warning restore 612, 618
        }
    }
}
